### ISSUE TITLE
_.createAggregator is not a function in Lodash 4.15.0

### ISSUE THREAD

**Issue by bkoplin** [Sigfried/supergroup#11]
supergroup.js @ 719 uses _.createAggregator to create the multiValuedGroupBy function. _.createAggregator doesn't seem to be a function in Lodash 4.15.0, so supergroup.js keeps throwing the error. Thoughts? Should I use underscore.js?

**Comment by Sigfried** [comment]
I don't know if underscore has it at all. But I believe this is fixed in https://github.com/Sigfried/supergroup/commit/cecc70a845b7de2388e55d587933771af898e2f5.
