### ISSUE TITLE
How can I help?

### ISSUE THREAD

**Issue by bkoplin** [Sigfried/supergroup#12]
@Sigfried: how can I help with _.supergroup? What have you wanted to develop but haven't got around to?

**Comment by Sigfried** [comment]
Hey Ben,

My email is sigfried@sigfried.org. I'm going to delete this comment right away so I'm not leaving my email here, but you should receive a notification of this message before it gets deleted, I think.

s

**Comment by Sigfried** [comment]
Arranging to talk offline. But now that there's someone else to pitch in, I'll start using issues to log bugs and feature requests.
